- name: Remove new hosts from known hosts file
  hosts: localhost
  tasks:
    - name: Remove them from hosts
      ansible.builtin.debug:
        msg: "{{ hostvars[groups['tag_k3s_master'][0]]['ansible_host'] }}"
    - name: Remove them from hosts
      ansible.builtin.debug:
        msg: "{{ groups['tag_k3s'] | map('extract', hostvars, ['ansible_host']) }}"
