- name: Remove all refs to new IPs from known hosts file
  hosts: localhost
  tasks:
    - name: Remove them from hosts
      ansible.builtin.lineinfile:
        path: /home/ian/.ssh/known_hosts
        state: absent
        regexp: "^{{ item }}"
      with_items: "{{ groups['all'] }}"

- name: Install and enable k3s on master node
  hosts: master
  remote_user: root
  roles:
    - master

- name: Install and enable k3s on the worker nodes
  hosts: workers
  remote_user: root
  vars:
    join_token: "{{ hostvars[groups['master'][0]].join_token }}"
    join_url: "https://{{ groups['master'][0] }}:6443"
  roles:
    - worker
    
- name: Bootstrap cluster
  hosts: master
  remote_user: root
  tasks:
    - name: Gather vars from sops file
      community.sops.load_vars:
        file: ../secrets.yaml
        name: secrets
      delegate_to: localhost

    - name: Running bootstrap role
      vars:
        role_id: "{{ secrets.vault_admin_role_id }}"
        secret_id: "{{ secrets.vault_admin_secret_id }}"
      include_role:
        name: bootstrap

#- name: Bootstrap cluster
#  hosts: master
#  remote_user: root
#  vars:
#    role_id: 6de70933-d865-9ed9-eb54-41fe2a3cba06
#    secret_id: 4ce79284-8e14-dfc8-a4cc-a81ba20b6712
#  roles:
#    - bootstrap
#
#- name: Extra
#  hosts: localhost
#  tasks:
#    - name: Print it
#      ansible.builtin.debug:
#        msg: "{{ hostvars[groups['master'][0]].join_token }}"
#
#    - name: Write the fucker
#      ansible.builtin.copy:
#        content: "{{ hostvars[groups['master'][0]] }}"
#        dest: "/home/ian/hostvars"
#
#    - name: Write the fucker
#      ansible.builtin.copy:
#        content: "{{ groups }}"
#        dest: "/home/ian/goups"
